### ISSUE TITLE
[Bug] Breaks monorepo lerna run command

### ISSUE THREAD

**Issue by lamaks** [antongolub/yarn-audit-fix#147]
When installing `yarn-audit-fix` package under monorepo any `lerna run` command that is defined in child packages as well will fail with error below.

For example, child package has script named `cbuild` within package.json. The root package.json has script named `cbuild` as well that defined as `lerna run cbuild`. When run `yarn cbuild` from monorepo root folder the above command hangs with similar error below.

Expected any script related lerna run command runs on all child packages under monorepo.

internal/modules/cjs/loader.js:968
   throw err;
   ^
 Error: Cannot find module '.../packages/...'
     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
     at Function.Module._load (internal/modules/cjs/loader.js:841:27)
     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
     at internal/main/run_main_module.js:17:47 {
   code: 'MODULE_NOT_FOUND',
   requireStack: []
 }

**Comment by antongolub** [comment]
Hey, @lamaks,

No idea, what might have broken. We [use](https://github.com/qiwi/substrate/blob/c9285f957dd67266d222da31d99e95359ce1c443/package.json#L25) **yarn-audit-fix** with **lerna** this like `"postupdate": "yarn && yarn bootstrap && npm_config_yes=true npx yarn-audit-fix && yarn build && yarn test"` — just same as you described —  and it works fine.
Could you add a more detailed setup that illustrates the issue? Or maybe you have a public repo?

**Comment by antongolub** [comment]
@lamaks,

Perhaps, this is what you were looking for: https://github.com/txantslusam/lerna-audit-yarn.
