### ISSUE TITLE
yarn-audit-fix command not found

### ISSUE THREAD

**Issue by NOBLEGG** [antongolub/yarn-audit-fix#27]
I installed this using `yarn add yarn-audit-fix -D` command.

But when I type `yarn-audit-fix`, Ubuntu gives me that `command not found`.

Do I have to modify env?

**Comment by antongolub** [comment]
@NOBLEGG

This is probably an issue with finding `node_modules/.bin` contents.
But you're able to run the cmd through **yarn**: `yarn yarn-audit-fix`.

**Comment by antongolub** [comment]
@NOBLEGG

I've added a note to the readme, so I'm closing this issue.
