### ISSUE TITLE
Temporary dowgrading __metadata version from 6 to 5 during run

### ISSUE THREAD

**Issue by ssbarnea** [antongolub/yarn-audit-fix#287]
I observed that that when using yarn-audit-fix as a pre-commit hook it does temporary downgrades the metadata version from my current 6 to 5 but it does put it back after.
```
__metadata:
  version: 5
```

This is still a bug as the file should not be modified during run if that is not needed.

**Comment by antongolub** [comment]
@ssbarnea,

Well, I agree, `__metadata` mutation seems redundant.

**Comment by ssbarnea** [comment]
@antongolub Thanks! That was blazing fast reaction! Added a bit of sunshine to what was looking like boring working day.
