### ISSUE TITLE
yarn-audit-fix isMonorepo

### ISSUE THREAD

**Issue by rexizam** [antongolub/yarn-audit-fix#319]
Hi, I'm using yarn-audit-fix in an NX monorepo. When I run the script the output says the following:

isMonorepo false
  bins 
    yarn yarn
    npm npm
  
  versions 
    node v18.13.0
    npm 9.8.1
    yarn 1.22.19
    yaf 10.0.1
    yafLatest 10.0.7

I was just wondering why isMonorepo is set to false and if it has something to do with package/directory level dependencies. I couldn't find anything about that in the documentation so that's why I'm asking here.

**Comment by antongolub** [comment]
@rexizam,

yaf monorepo detection [is based on `workplaces` field of package.json](https://github.com/antongolub/yarn-audit-fix/blob/master/src/main/ts/stages.ts#L60). nx just traverses the `<cwd>/packages` folder, right?

**Comment by rexizam** [comment]
Great, thank you for the information. I wasn't aware of that part in the source code.
