### ISSUE TITLE
npmrc is not copied over to help with private npm feeds

### ISSUE THREAD

**Issue by sushruth** [antongolub/yarn-audit-fix#34]
copying over any `.npmrc` in the project while copying package.json helps work with private feeds.

**Comment by sushruth** [comment]
Update - even after copying, turns out, using regular npm registry is the best idea - 

```
npm audit --registry=https://registry.npmjs.org/
```

**Comment by antongolub** [comment]
Hey, @sushruth, 

thanks for the useful tip. Do you want to make a PR?

**Comment by sushruth** [comment]
Yep, I can.

**Comment by antongolub** [comment]
@sushruth,

Great! If you need help, just let me know.

**Comment by antongolub** [comment]
Hey, @sushruth,

I've added .npmrc/.yarnrc copying and `--registry` flag handling.
Can confirm that everything works as you expected?
