### ISSUE TITLE
high severity vulnerability in cross-spawn

### ISSUE THREAD

**Issue by Zanaxhir** [antongolub/yarn-audit-fix#350]
# npm audit report

cross-spawn  <6.0.6
Severity: high
Regular Expression Denial of Service (ReDoS) in cross-spawn - https://github.com/advisories/GHSA-3xgq-45jj-v275

 Path:   yarn-audit-fix > synp > bash-glob > cross-spawn

**Comment by antongolub** [comment]
https://github.com/imsnif/synp/pull/108
