### ISSUE TITLE
Bug: workspaces configuration is being removed if INT signal was sent in the middle

### ISSUE THREAD

**Issue by PatrykMilewski** [antongolub/yarn-audit-fix#6]
Hello!

After running yarn-audit-fix, my configuration of Yarn Workspaces from package.json file is removed, if I send INT signal, when yarn-audit-fix is still working.

I believe it's due to creating a copy of package.json (origin.package.json) which overwrites package.json file and removes workspaces configuration. 
I believe it would be safer to never overwrite package.json file, since process of fixing audit takes some time and it's very common to interrupt it in the middle of it.

I'm using 1.3.0 version.

**Comment by antongolub** [comment]
@PatrykMilewski 
Hi.

I agree, it's a bit annoying. I thought about moving all interactions to some temp directory, but this also requires `node_modules` to be copied due to `npm audit fix`. I'll try to work around this with a symlink.

**Comment by antongolub** [comment]
@PatrykMilewski

Do you want a test drive? `yarn-audit-fix@1.4.0-beta.1`

**Comment by PatrykMilewski** [comment]
@antongolub Works great! Just tested it! Thank you
